network:
  n_vertices: 20
  avg_degree: 4
  network_type: random # random, small-world, scale-free
  interaction_type: random # random, mutualism, competition, predator-prey, mix
  max_interaction_strength: 1.0

simulation:
  time_points: 1000
  time_step: 0.01
  downsample: 20
  noise_var: 0.01
  scale_simulation: 10

path:
  data_dir: data/simulated